# Generated by Django 4.1.5 on 2023-01-19 16:08

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('\\d{3}')])),
                ('class_name', models.CharField(max_length=50)),
                ('classImgs', models.FileField(max_length=300, null=True, upload_to='')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=60, unique=True)),
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(4)(\\d{7})$')])),
                ('student_absence', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='date registered')),
                ('classes', models.ManyToManyField(to='HadirApp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(default=None, null=True, upload_to='media/Students')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HadirApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence_date', models.DateField(default=datetime.date.today)),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HadirApp.class')),
                ('student', models.ManyToManyField(to='HadirApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HadirApp.class')),
                ('date', models.ManyToManyField(to='HadirApp.date')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HadirApp.student')),
            ],
        ),
    ]
