# Generated by Django 3.2.5 on 2023-01-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0002_class_num_of_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(default='/HadirApp/static/Hadir/media/user.png', upload_to=''),
        ),
    ]
