# Generated by Django 3.2.5 on 2023-01-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0003_student_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
