# Generated by Django 3.2.5 on 2023-01-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0004_alter_student_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default=None, null=True, upload_to='media/Traning')),
            ],
        ),
    ]
