# Generated by Django 3.2.5 on 2023-01-24 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0005_traning'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
