# Generated by Django 3.2.5 on 2023-01-24 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0008_auto_20230124_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Creation_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date registered'),
        ),
    ]
