# Generated by Django 3.2.5 on 2023-01-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0009_auto_20230124_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
