# Generated by Django 3.2.5 on 2023-01-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0011_auto_20230124_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_absence',
        ),
    ]
